### ISSUE TITLE
Player hangs when stopping (alsa output plugin)

### ISSUE THREAD

**Issue by saivert** [DeaDBeeF-Player/deadbeef#1768]
This isn't easily reproducible. Sometimes I have to click play and stop over 10 times.

It looks like a mutex lock is the culprit e.g in palsa_stop() function.

```
(gdb) thread 26
[Switching to thread 26 (Thread 0x7fffb9732700 (LWP 15784))]
#0  0x00007ffff76b5d8c in __lll_lock_wait () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007ffff76b5d8c in __lll_lock_wait () at /usr/lib/libpthread.so.0
#1  0x00007ffff76aeb96 in pthread_mutex_lock () at /usr/lib/libpthread.so.0
#2  0x0000000000417166 in mutex_lock (_mtx=<optimized out>) at threading_pthread.c:172
#3  0x00000000004132b7 in streamer_lock () at streamer.c:149
#4  0x00000000004132b7 in streamer_read (bytes=0x7fffb972ff00 "\036̤\275㟚=l\002\344\275֪\211=\327\004\031\276J\202'=\317\351\064\276\374\032l;\265).\276\024U\026\275\064c\031\276\061\204\216\275\361H\362\275\260\235\244\275", size=8192) at streamer.c:1669
#5  0x00007fffe8d2a2fc in palsa_callback (len=8192, stream=0x7fffb972ff00 "\036̤\275㟚=l\002\344\275֪\211=\327\004\031\276J\202'=\317\351\064\276\374\032l;\265).\276\024U\026\275\064c\031\276\061\204\216\275\361H\362\275\260\235\244\275") at alsa.c:653
#6  0x00007fffe8d2a2fc in palsa_thread (context=<optimized out>) at alsa.c:589
#7  0x00007ffff76ac2e7 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff73ed54f in clone () at /usr/lib/libc.so.6
(gdb) thread 6
[Switching to thread 6 (Thread 0x7fffd2e4a700 (LWP 15722))]
#0  0x00007ffff76b5d8c in __lll_lock_wait () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007ffff76b5d8c in __lll_lock_wait () at /usr/lib/libpthread.so.0
#1  0x00007ffff76aeb96 in pthread_mutex_lock () at /usr/lib/libpthread.so.0
#2  0x0000000000417166 in mutex_lock (_mtx=<optimized out>) at threading_pthread.c:172
#3  0x00007fffe8d2a5b2 in palsa_stop () at alsa.c:531
#4  0x0000000000413044 in play_index (idx=-1) at streamer.c:1951
#5  0x0000000000413044 in streamer_thread (ctx=<optimized out>) at streamer.c:1307
#6  0x00007ffff76ac2e7 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007ffff73ed54f in clone () at /usr/lib/libc.so.6
(gdb) 
```
Thread 6 is streamer-thread and thread 26 is alsa plugin thread.

**Comment by kuba160** [comment]
I think i encounter the same problem with pulseaudio plugin. When I start music and later press button to stop it, music does not stop. Doesn't happen all the time but quite often. Player does not respond to any music action (buttons and song change).

```
(gdb) thread apply all bt

Thread 14 (Thread 0x7fffbe7fc700 (LWP 10517)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff6c584c3 in loading_thread (none=<optimized out>) at coverart.c:405
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffbe7fc700) at pthread_create.c:333
#3  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 13 (Thread 0x7fffbeffd700 (LWP 10516)):
#0  0x00007ffff73f54ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff474c9f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff474cd82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4f36656 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff47743d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff76bb494 in start_thread (arg=0x7fffbeffd700) at pthread_create.c:333
#6  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 12 (Thread 0x7fffbf7fe700 (LWP 10515)):
#0  0x00007ffff73f54ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff474c9f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff474cb0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff474cb51 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff47743d5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff76bb494 in start_thread (arg=0x7fffbf7fe700) at pthread_create.c:333
#6  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 10 (Thread 0x7fffbffff700 (LWP 10513)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff76bdc06 in __GI___pthread_mutex_lock (mutex=0x555555916ad0)
    at ../nptl/pthread_mutex_lock.c:115
#2  0x000055555559c486 in mutex_lock (_mtx=<optimized out>) at threading_pthread.c:172
#3  0x00007fffeab7b098 in pulse_free () at pulse.c:209
#4  0x00007fffeab7b123 in pulse_pause () at pulse.c:255
#5  0x0000555555589750 in player_mainloop () at main.c:656
#6  0x0000555555589979 in mainloop_thread (ctx=<optimized out>) at main.c:812
#7  0x00007ffff76bb494 in start_thread (arg=0x7fffbffff700) at pthread_create.c:333
#8  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 9 (Thread 0x7fffdcee0700 (LWP 10512)):
#0  0x00007ffff73f7233 in select () at ../sysdeps/unix/syscall-template.S:84
#1  0x00005555555894bd in server_loop (ctx=<optimized out>) at main.c:564
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffdcee0700) at pthread_create.c:333
#3  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 8 (Thread 0x7fffdd6e1700 (LWP 10511)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:143
#1  0x00007fffe3649278 in pa_threaded_mainloop_wait () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007fffe3868cb2 in pa_simple_write () from /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0
#3  0x00007fffeab7afa4 in pulse_thread (context=<optimized out>) at pulse.c:315
#4  0x00007ffff76bb494 in start_thread (arg=0x7fffdd6e1700) at pthread_create.c:333
#5  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 7 (Thread 0x7fffebcc8700 (LWP 10510)):
#0  0x00007ffff73f54ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fffe3648c91 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
---Type <return> to continue, or q <return> to quit---
#2  0x00007fffe363a4a1 in pa_mainloop_poll () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007fffe363ab3e in pa_mainloop_iterate () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007fffe363abf0 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007fffe3648bd9 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007fffe33e82c8 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-10.0.so
#7  0x00007ffff76bb494 in start_thread (arg=0x7fffebcc8700) at pthread_create.c:333
#8  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 6 (Thread 0x7fffddee2700 (LWP 10509)):
#0  0x00007ffff73ce08d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff73f79f4 in usleep (useconds=useconds@entry=50000) at ../sysdeps/posix/usleep.c:32
#2  0x0000555555597b36 in streamer_thread (ctx=<optimized out>) at streamer.c:1390
#3  0x00007ffff76bb494 in start_thread (arg=0x7fffddee2700) at pthread_create.c:333
#4  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 5 (Thread 0x7fffde6e3700 (LWP 10508)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000055555559c58b in cond_wait (c=93824996174048, m=93824996174000) at threading_pthread.c:217
#2  0x00007fffe8e99371 in lfm_thread (ctx=<optimized out>) at lastfm.c:735
#3  0x00007ffff76bb494 in start_thread (arg=0x7fffde6e3700) at pthread_create.c:333
#4  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 4 (Thread 0x7fffdeee4700 (LWP 10507)):
#0  0x00007ffff73ce08d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff73f79f4 in usleep (useconds=useconds@entry=200000) at ../sysdeps/posix/usleep.c:32
#2  0x00007fffe9372d8f in hotkeys_event_loop (unused=<optimized out>) at hotkeys.c:498
#3  0x00007ffff76bb494 in start_thread (arg=0x7fffdeee4700) at pthread_create.c:333
#4  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 3 (Thread 0x7fffdf6e5700 (LWP 10506)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x00007fffec5d07af in cache_cleaner_thread (none=<optimized out>) at cache.c:182
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffdf6e5700) at pthread_create.c:333
#3  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 2 (Thread 0x7fffdfee6700 (LWP 10505)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fffec5d00f1 in fetcher_thread (none=<optimized out>) at artwork.c:1838
#2  0x00007ffff76bb494 in start_thread (arg=0x7fffdfee6700) at pthread_create.c:333
#3  0x00007ffff73fe93f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 1 (Thread 0x7ffff7fb7e80 (LWP 10504)):
#0  0x00007ffff73f54ed in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff474c9f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff474cd82 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff64e4d55 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#4  0x00007ffff6c2a3ea in gtkui_thread (ctx=ctx@entry=0x0) at gtkui.c:1337
#5  0x00007ffff6c2a64c in gtkui_start () at gtkui.c:1489
#6  0x0000555555588169 in main (argc=<optimized out>, argv=<optimized out>) at main.c:1160
```

**Comment by Alexey-Yakovenko** [comment]
This should be fixed.
