### ISSUE TITLE
Can't open deadbeef, please help

### ISSUE THREAD

**Issue by JulianLai** [DeaDBeeF-Player/deadbeef#1881]
### Steps to reproduce the problem
run deadbeef
### What's going on? Describe the problem in as much detail as possible.
```
[user@user-PC ~]$ gdb deadbeef 
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from deadbeef...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/deadbeef 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
starting deadbeef 0.7.2
server_start
searching for GUI plugins in /home/user/.local/lib64/deadbeef
searching for GUI plugins in /home/user/.local/lib/deadbeef
searching for GUI plugins in /usr/lib/deadbeef
load_plugin_dir /usr/lib/deadbeef: scandir found 57 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /usr/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/user/.local/lib64/deadbeef
loading plugins from /home/user/.local/lib/deadbeef
loading plugins from /usr/lib/deadbeef
load_plugin_dir /usr/lib/deadbeef: scandir found 57 files
loading plugin /usr/lib/deadbeef/aac.so
loading plugin /usr/lib/deadbeef/adplug.so
loading plugin /usr/lib/deadbeef/alac.so
loading plugin /usr/lib/deadbeef/alsa.so
loading plugin /usr/lib/deadbeef/artwork.so
loading plugin /usr/lib/deadbeef/cdda.so
loading plugin /usr/lib/deadbeef/converter.so
loading plugin /usr/lib/deadbeef/converter_gtk2.so
loading plugin /usr/lib/deadbeef/converter_gtk3.so
loading plugin /usr/lib/deadbeef/dca.so
loading plugin /usr/lib/deadbeef/ddb_ao.so
loading plugin /usr/lib/deadbeef/ddb_bs2b.so
loading plugin /usr/lib/deadbeef/ddb_dumb.so
loading plugin /usr/lib/deadbeef/ddb_misc_replaygain_scan.so
loading plugin /usr/lib/deadbeef/ddb_misc_replaygain_scan_GTK2.so
loading plugin /usr/lib/deadbeef/ddb_misc_replaygain_scan_GTK3.so
loading plugin /usr/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib/deadbeef/ddb_shn.so
loading plugin /usr/lib/deadbeef/dsp_libsrc.so
loading plugin /usr/lib/deadbeef/ffap.so
loading plugin /usr/lib/deadbeef/ffmpeg.so
loading plugin /usr/lib/deadbeef/flac.so
loading plugin /usr/lib/deadbeef/gme.so
loading plugin /usr/lib/deadbeef/hotkeys.so
loading plugin /usr/lib/deadbeef/in_sc68.so
loading plugin /usr/lib/deadbeef/lastfm.so
loading plugin /usr/lib/deadbeef/m3u.so
loading plugin /usr/lib/deadbeef/mms.so
loading plugin /usr/lib/deadbeef/mp3.so
loading plugin /usr/lib/deadbeef/mpris.so
loading plugin /usr/lib/deadbeef/musepack.so
loading plugin /usr/lib/deadbeef/notify.so
loading plugin /usr/lib/deadbeef/nullout.so
loading plugin /usr/lib/deadbeef/oss.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /usr/lib/deadbeef/pulse.so
loading plugin /usr/lib/deadbeef/shellexec.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk2.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk3.so
loading plugin /usr/lib/deadbeef/sid.so
loading plugin /usr/lib/deadbeef/sndfile.so
loading plugin /usr/lib/deadbeef/supereq.so
loading plugin /usr/lib/deadbeef/tta.so
loading plugin /usr/lib/deadbeef/vfs_curl.so
loading plugin /usr/lib/deadbeef/vfs_zip.so
loading plugin /usr/lib/deadbeef/vorbis.so
loading plugin /usr/lib/deadbeef/vtx.so
loading plugin /usr/lib/deadbeef/wavpack.so
loading plugin /usr/lib/deadbeef/wildmidi.so
loading plugin /usr/lib/deadbeef/wma.so
[New Thread 0x7fffd7039700 (LWP 8062)]
[New Thread 0x7fffd6838700 (LWP 8063)]
[New Thread 0x7fffd5f78700 (LWP 8064)]
[New Thread 0x7fffd5777700 (LWP 8065)]
[New Thread 0x7fffd4f76700 (LWP 8066)]
[New Thread 0x7fffcffff700 (LWP 8067)]
[New Thread 0x7fffcf7fe700 (LWP 8068)]
[New Thread 0x7fffceffd700 (LWP 8069)]
**
GLib-GIO:ERROR:gdbusconnection.c:4154:invoke_get_property_in_idle_cb: assertion failed: (error != NULL)

Thread 6 "mpris-listener" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffd4f76700 (LWP 8066)]
0x00007ffff72e78a0 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff72e78a0 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff72e8f09 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff49accbd in g_assertion_message () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff49acd4a in g_assertion_message_expr () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff51612f6 in  () at /usr/lib/libgio-2.0.so.0
#5  0x00007ffff49868c5 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff4986c88 in  () at /usr/lib/libglib-2.0.so.0
#7  0x00007ffff4986fa2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#8  0x00007fffdad0c8f3 in startServer () at /usr/lib/deadbeef/mpris.so
#9  0x00007ffff49adae5 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#11 0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6
```
### Information about the software:
```
名稱                   : deadbeef
版本                   : 0.7.2-2
描述                   : A GTK+ audio player for GNU/Linux.
硬體架構               : x86_64
URL                    : http://deadbeef.sourceforge.net
軟體授權               : GPL2
群組                   : 無
它提供                 : 無
它依賴                 : alsa-lib  hicolor-icon-theme  desktop-file-utils  jansson
可選依賴               : gtk2: for the GTK2 interface [已安裝]
                         gtk3: for the GTK3 interface [已安裝]
                         libsamplerate: for Resampler plugin [已安裝]
                         libvorbis: for Ogg Vorbis playback [已安裝]
                         libmad: for MP1/MP2/MP3 playback [已安裝]
                         mpg123: for MP1/MP2/MP3 playback
                         flac: for FLAC playback [已安裝]
                         curl: for Last.fm scrobbler, SHOUTcast, Icecast, Podcast support [已安裝]
                         imlib2: for artwork plugin [已安裝]
                         wavpack: for WavPack playback [已安裝]
                         libsndfile: for Wave playback [已安裝]
                         libcdio: audio cd plugin [已安裝]
                         libcddb: audio cd plugin [已安裝]
                         faad2: for AAC/MP4 support [已安裝]
                         dbus: for OSD notifications support [已安裝]
                         pulseaudio: for PulseAudio output plugin [已安裝]
                         libx11: for global hotkeys plugin [已安裝]
                         zlib: for Audio Overload plugin [已安裝]
                         libzip: for vfs_zip plugin [已安裝]
                         ffmpeg: for ffmpeg plugin [已安裝]
需要它                 : deadbeef-mpris2-plugin  deadbeef-replaygain-scan-git
為這些軟體包的可選依賴 : 無
與它衝突               : 無
它會取代               : 無
安裝後大小             : 9.67 MiB
打包者                 : Laurent Carlier <lordheavym@gmail.com>
建置日期               : 西元2017年03月13日 (週一) 14時21分00秒
安裝日期               : 西元2017年06月09日 (週五) 11時49分02秒
安裝原因               : 單獨指定安裝
安裝指令稿             : 否
驗證者                 : 簽章
```

Deadbeef version: 0.7.2-2
OS: Antergos

**Comment by JulianLai** [comment]
The problem is suddenly gone...
