### ISSUE TITLE
It crashes when I try to play dsf audio

### ISSUE THREAD

**Issue by JulianLai** [DeaDBeeF-Player/deadbeef#1892]
### Steps to reproduce the problem
play dsf audio
### What's going on? Describe the problem in as much detail as possible.
![deepinscreenshot_20170926114923](https://user-images.githubusercontent.com/20014762/30841818-cc239b4c-a2b0-11e7-8f43-051f0fa1eb2f.png)

It crashes
```
[user@user-PC ~]$ gdb deadbeef 
GNU gdb (GDB) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from deadbeef...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/deadbeef 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
starting deadbeef devel
installdir: /usr
confdir: /home/user/.config
docdir: /usr/share/doc/deadbeef
plugindir: /usr/lib/deadbeef
pixmapdir: /usr/share/deadbeef/pixmaps
server_start
searching for GUI plugins in /home/user/.local/lib64/deadbeef
searching for GUI plugins in /home/user/.local/lib/deadbeef
searching for GUI plugins in /usr/lib/deadbeef
load_plugin_dir /usr/lib/deadbeef: scandir found 56 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /usr/lib/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/user/.local/lib64/deadbeef
loading plugins from /home/user/.local/lib/deadbeef
loading plugins from /usr/lib/deadbeef
load_plugin_dir /usr/lib/deadbeef: scandir found 56 files
loading plugin /usr/lib/deadbeef/aac.so
loading plugin /usr/lib/deadbeef/adplug.so
loading plugin /usr/lib/deadbeef/alac.so
loading plugin /usr/lib/deadbeef/alsa.so
loading plugin /usr/lib/deadbeef/artwork.so
loading plugin /usr/lib/deadbeef/cdda.so
loading plugin /usr/lib/deadbeef/converter.so
loading plugin /usr/lib/deadbeef/converter_gtk2.so
loading plugin /usr/lib/deadbeef/converter_gtk3.so
loading plugin /usr/lib/deadbeef/dca.so
loading plugin /usr/lib/deadbeef/ddb_bs2b.so
loading plugin /usr/lib/deadbeef/ddb_dumb.so
loading plugin /usr/lib/deadbeef/ddb_mono2stereo.so
loading plugin /usr/lib/deadbeef/ddb_shn.so
loading plugin /usr/lib/deadbeef/dsp_libsrc.so
loading plugin /usr/lib/deadbeef/ffap.so
loading plugin /usr/lib/deadbeef/ffmpeg.so
loading plugin /usr/lib/deadbeef/flac.so
loading plugin /usr/lib/deadbeef/gme.so
loading plugin /usr/lib/deadbeef/hotkeys.so
loading plugin /usr/lib/deadbeef/in_sc68.so
loading plugin /usr/lib/deadbeef/jack.so
loading plugin /usr/lib/deadbeef/lastfm.so
loading plugin /usr/lib/deadbeef/m3u.so
loading plugin /usr/lib/deadbeef/mms.so
loading plugin /usr/lib/deadbeef/mp3.so
loading plugin /usr/lib/deadbeef/mpris.so
loading plugin /usr/lib/deadbeef/musepack.so
loading plugin /usr/lib/deadbeef/notify.so
loading plugin /usr/lib/deadbeef/nullout.so
loading plugin /usr/lib/deadbeef/oss.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk2.so
loading plugin /usr/lib/deadbeef/pltbrowser_gtk3.so
loading plugin /usr/lib/deadbeef/psf.so
loading plugin /usr/lib/deadbeef/pulse.so
loading plugin /usr/lib/deadbeef/rg_scanner.so
loading plugin /usr/lib/deadbeef/shellexec.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk2.so
loading plugin /usr/lib/deadbeef/shellexecui_gtk3.so
loading plugin /usr/lib/deadbeef/sid.so
loading plugin /usr/lib/deadbeef/sndfile.so
loading plugin /usr/lib/deadbeef/supereq.so
loading plugin /usr/lib/deadbeef/tta.so
loading plugin /usr/lib/deadbeef/vfs_curl.so
loading plugin /usr/lib/deadbeef/vfs_zip.so
loading plugin /usr/lib/deadbeef/vorbis.so
loading plugin /usr/lib/deadbeef/vtx.so
loading plugin /usr/lib/deadbeef/wavpack.so
loading plugin /usr/lib/deadbeef/wildmidi.so
loading plugin /usr/lib/deadbeef/wma.so
[New Thread 0x7fffd6b7a700 (LWP 3131)]
[New Thread 0x7fffd6379700 (LWP 3132)]
[New Thread 0x7fffd5ab9700 (LWP 3133)]
[New Thread 0x7fffd52b8700 (LWP 3134)]
[New Thread 0x7fffd4ab7700 (LWP 3135)]
[New Thread 0x7fffcffff700 (LWP 3136)]
selected output plugin: PulseAudio output plugin
INFO: from file /home/user/.config/deadbeef/playlists/0.dbpl
[New Thread 0x7fffcf7fe700 (LWP 3137)]
[New Thread 0x7fffceffd700 (LWP 3138)]
[New Thread 0x7fffce7fc700 (LWP 3139)]
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
plugin Playlist browser GTK2 failed to connect to dependencies, deactivated.
shellexecui: can't find gtkui plugin
plugin Shellexec GTK2 UI failed to connect to dependencies, deactivated.
[New Thread 0x7fffeb3ae700 (LWP 3140)]
[New Thread 0x7fffcdffb700 (LWP 3141)]
gtkui plugin compiled for gtk version: 3.22.21
connecting button tray signals
[New Thread 0x7fffbae1d700 (LWP 3142)]
[New Thread 0x7fffba014700 (LWP 3143)]
[dsf @ 0x7fff98021260] Unknown encoding
[dsf @ 0x7fff98021260] Estimating duration from bitrate, this may be inaccurate
[New Thread 0x7fffb9813700 (LWP 3152)]
[New Thread 0x7fffb9012700 (LWP 3153)]
[Thread 0x7fffb9813700 (LWP 3152) exited]
Assertion 'p' failed at pulse/simple.c:273, function pa_simple_write(). Aborting.

Thread 16 "deadbeef-pulse" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb9012700 (LWP 3153)]
0x00007ffff72e78a0 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff72e78a0 in raise () at /usr/lib/libc.so.6
(gdb) 

```
### Information about the software:
```
Name            : deadbeef-git
Version         : r7392.6a0a9b9a-1
Description     : Music player based on GTK2 (devel branch)
Architecture    : x86_64
URL             : http://deadbeef.sourceforge.net
Licenses        : GPL2
Groups          : None
Provides        : deadbeef
Depends On      : alsa-lib  desktop-file-utils  gtk2  gtk3  hicolor-icon-theme  gtkglext  jansson
Optional Deps   : libsamplerate: for dsp_libsrc plugin (resampler) [installed]
                  libsm: optional dependency for gtkui session client support [installed]
                  libice: optional dependency for gtkui session client support [installed]
                  alsa-lib: ALSA support [installed]
                  alsa-oss: for OSS output plugin
                  libvorbis: for ogg vorbis plugin [installed]
                  libogg: for ogg vorbis plugin [installed]
                  libmad: for mp3 plugin (mpeg1,2 layers1,2,3) [installed]
                  flac: for flac plugin [installed]
                  curl: for last.fm, vfs_curl (shoutcast/icecast), artwork plugins [installed]
                  imlib2: for artwork plugin [installed]
                  wavpack: for wavpack plugin [installed]
                  libsndfile: for sndfile plugin [installed]
                  libcdio: for cd audio plugin [installed]
                  libcddb: for cd audio plugin [installed]
                  faad2: for AAC plugin [installed]
                  dbus: for notification daemon support (OSD current song notifications) [installed]
                  pulseaudio: for PulseAudio output plugin [installed]
                  libx11: for global hotkeys plugin [installed]
                  zlib: for Audio Overload plugin (psf, psf2, etc), GME (for vgz) [installed]
                  libsidplay: for SID player plugin
                  yasm: required to build assembly portions of ffap plugin [installed]
                  libzip: for vfs_zip plugin [installed]
Required By     : deadbeef-jack-git  deadbeef-mpris2-plugin
Optional For    : None
Conflicts With  : deadbeef
Replaces        : None
Installed Size  : 10.72 MiB
Packager        : Unknown Packager
Build Date      : Tue Sep 26 02:05:40 2017
Install Date    : Tue Sep 26 02:06:04 2017
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None

```
Deadbeef version: r7392.6a0a9b9a-1
OS: Antergos

**Comment by Alexey-Yakovenko** [comment]
Please provide backtrace. Instructions on wiki: https://github.com/DeaDBeeF-Player/deadbeef/wiki/GDB-HOWTO

**Comment by JulianLai** [comment]
@Alexey-Yakovenko 
```
Thread 16 (Thread 0x7fffb9813700 (LWP 14279)):
#0  0x00007ffff72e78a0 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff72e8f09 in abort () at /usr/lib/libc.so.6
#2  0x00007fffd9a22b9f in pa_simple_write () at /usr/lib/libpulse-simple.so.0
#3  0x00007fffd9c25d48 in  () at /usr/lib/deadbeef/pulse.so
#4  0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6

Thread 14 (Thread 0x7fffba014700 (LWP 14261)):
#0  0x00007ffff739ecbb in poll () at /usr/lib/libc.so.6
#1  0x00007fffd9803773 in  () at /usr/lib/libpulse.so.0
#2  0x00007fffd97f4bd0 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007fffd97f5271 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007fffd97f5301 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007fffd98036ae in  () at /usr/lib/libpulse.so.0
#6  0x00007fffd95a281c in  () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#7  0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6

Thread 13 (Thread 0x7fffbae1d700 (LWP 14258)):
#0  0x00007ffff767738d in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007ffff6e5060e in  () at /usr/lib/deadbeef/ddb_gui_GTK3.so
#2  0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6

Thread 12 (Thread 0x7fffcdffb700 (LWP 14257)):
#0  0x00007ffff767738d in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
---Type <return> to continue, or q <return> to quit---
#1  0x000055555559dbcb in  ()
#2  0x000055555559c757 in  ()
#3  0x0000555555589529 in  ()
#4  0x00005555555896c9 in  ()
#5  0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7fffeb3ae700 (LWP 14256)):
#0  0x00007ffff73a0af3 in select () at /usr/lib/libc.so.6
#1  0x00005555555891c7 in  ()
#2  0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7fffce7fc700 (LWP 14255)):
#0  0x00007ffff7377190 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff73a1404 in usleep () at /usr/lib/libc.so.6
#2  0x0000555555599b12 in  ()
#3  0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7fffceffd700 (LWP 14254)):
#0  0x00007ffff4905980 in g_bit_lock () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff496b193 in g_variant_ref_sink () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff4964224 in g_variant_new_variant () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff4f0d22b in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff4f0ce79 in  () at /usr/lib/libgio-2.0.so.0
#5  0x00007ffff4f0d14d in  () at /usr/lib/libgio-2.0.so.0
#6  0x00007ffff4f0f043 in g_dbus_message_new_from_blob () at /usr/lib/libgio-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#7  0x00007ffff4f193fe in  () at /usr/lib/libgio-2.0.so.0
#8  0x00007ffff4ed5d53 in  () at /usr/lib/libgio-2.0.so.0
#9  0x00007ffff4ed5d89 in  () at /usr/lib/libgio-2.0.so.0
#10 0x00007ffff492f8c5 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#11 0x00007ffff492fc88 in  () at /usr/lib/libglib-2.0.so.0
#12 0x00007ffff492ffa2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#13 0x00007ffff4f17546 in  () at /usr/lib/libgio-2.0.so.0
#14 0x00007ffff4956ae5 in  () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#16 0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7fffcffff700 (LWP 14252)):
#0  0x00007ffff739ecbb in poll () at /usr/lib/libc.so.6
#1  0x00007ffff492fc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff492fd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff492fd61 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff4956ae5 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7fffd4ab7700 (LWP 14251)):
#0  0x00007ffff739ecbb in poll () at /usr/lib/libc.so.6
#1  0x00007ffff492fc09 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff492ffa2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007fffdadf68f3 in startServer () at /usr/lib/deadbeef/mpris.so
#4  0x00007ffff4956ae5 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6
---Type <return> to continue, or q <return> to quit---

Thread 5 (Thread 0x7fffd52b8700 (LWP 14250)):
#0  0x00007ffff767738d in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x000055555559dbcb in  ()
#2  0x00007fffdd581ae4 in  () at /usr/lib/deadbeef/lastfm.so
#3  0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7fffd5ab9700 (LWP 14249)):
#0  0x00007ffff7377190 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff73a1404 in usleep () at /usr/lib/libc.so.6
#2  0x00007fffddea71b0 in  () at /usr/lib/deadbeef/hotkeys.so
#3  0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffd6379700 (LWP 14248)):
#0  0x00007ffff7377190 in nanosleep () at /usr/lib/libc.so.6
#1  0x00007ffff73a1404 in usleep () at /usr/lib/libc.so.6
#2  0x00007fffec71ba4a in  () at /usr/lib/deadbeef/artwork.so
#3  0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffd6b7a700 (LWP 14247)):
#0  0x00007ffff767738d in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007fffec71b511 in  () at /usr/lib/deadbeef/artwork.so
#2  0x00007ffff767108a in start_thread () at /usr/lib/libpthread.so.0
#3  0x00007ffff73a91bf in clone () at /usr/lib/libc.so.6

---Type <return> to continue, or q <return> to quit---
Thread 1 (Thread 0x7ffff7fbab80 (LWP 14243)):
#0  0x00007fffef991efb in  () at /usr/lib/libharfbuzz.so.0
#1  0x00007fffef9b3a68 in  () at /usr/lib/libharfbuzz.so.0
#2  0x00007fffef983ce2 in hb_shape_plan_execute () at /usr/lib/libharfbuzz.so.0
#3  0x00007fffef9833f4 in hb_shape_full () at /usr/lib/libharfbuzz.so.0
#4  0x00007ffff365d910 in  () at /usr/lib/libpangoft2-1.0.so.0
#5  0x00007ffff5d85ac9 in pango_shape_full () at /usr/lib/libpango-1.0.so.0
#6  0x00007ffff5d77503 in  () at /usr/lib/libpango-1.0.so.0
#7  0x00007ffff5d79022 in  () at /usr/lib/libpango-1.0.so.0
#8  0x00007ffff5d7b4cd in  () at /usr/lib/libpango-1.0.so.0
#9  0x00007ffff5d7d0ae in  () at /usr/lib/libpango-1.0.so.0
#10 0x00007ffff5d7d5e4 in pango_layout_get_pixel_extents () at /usr/lib/libpango-1.0.so.0
#11 0x00007ffff5d7d647 in pango_layout_get_pixel_size () at /usr/lib/libpango-1.0.so.0
#12 0x00007ffff66c7ea7 in  () at /usr/lib/libgtk-3.so.0
#13 0x00007ffff66c83eb in  () at /usr/lib/libgtk-3.so.0
#14 0x00007ffff6617b13 in  () at /usr/lib/libgtk-3.so.0
#15 0x00007ffff661bd62 in  () at /usr/lib/libgtk-3.so.0
#16 0x00007ffff66c38a4 in  () at /usr/lib/libgtk-3.so.0
#17 0x00007ffff67854b1 in  () at /usr/lib/libgtk-3.so.0
#18 0x00007ffff678574c in  () at /usr/lib/libgtk-3.so.0
#19 0x00007ffff6785a55 in gtk_widget_get_preferred_height_and_baseline_for_width ()
    at /usr/lib/libgtk-3.so.0
#20 0x00007ffff65c4798 in  () at /usr/lib/libgtk-3.so.0
#21 0x00007ffff6617b13 in  () at /usr/lib/libgtk-3.so.0
#22 0x00007ffff661bd62 in  () at /usr/lib/libgtk-3.so.0
#23 0x00007ffff65c5144 in  () at /usr/lib/libgtk-3.so.0
#24 0x00007ffff67854b1 in  () at /usr/lib/libgtk-3.so.0
#25 0x00007ffff678574c in  () at /usr/lib/libgtk-3.so.0
---Type <return> to continue, or q <return> to quit---
#26 0x00007ffff6784ba1 in gtk_widget_get_preferred_height () at /usr/lib/libgtk-3.so.0
#27 0x00007ffff6690079 in  () at /usr/lib/libgtk-3.so.0
#28 0x00007ffff6617b13 in  () at /usr/lib/libgtk-3.so.0
#29 0x00007ffff661bd62 in  () at /usr/lib/libgtk-3.so.0
#30 0x00007ffff669029f in  () at /usr/lib/libgtk-3.so.0
#31 0x00007ffff6617b13 in  () at /usr/lib/libgtk-3.so.0
#32 0x00007ffff661bd62 in  () at /usr/lib/libgtk-3.so.0
#33 0x00007ffff66903d7 in  () at /usr/lib/libgtk-3.so.0
#34 0x00007ffff6784ead in  () at /usr/lib/libgtk-3.so.0
#35 0x00007ffff678574c in  () at /usr/lib/libgtk-3.so.0
#36 0x00007ffff6785a55 in gtk_widget_get_preferred_height_and_baseline_for_width ()
    at /usr/lib/libgtk-3.so.0
#37 0x00007ffff65c4798 in  () at /usr/lib/libgtk-3.so.0
#38 0x00007ffff6617b13 in  () at /usr/lib/libgtk-3.so.0
#39 0x00007ffff661bd62 in  () at /usr/lib/libgtk-3.so.0
#40 0x00007ffff65c5144 in  () at /usr/lib/libgtk-3.so.0
#41 0x00007ffff67854b1 in  () at /usr/lib/libgtk-3.so.0
#42 0x00007ffff678574c in  () at /usr/lib/libgtk-3.so.0
#43 0x00007ffff6785a55 in gtk_widget_get_preferred_height_and_baseline_for_width ()
    at /usr/lib/libgtk-3.so.0
#44 0x00007ffff65c4798 in  () at /usr/lib/libgtk-3.so.0
#45 0x00007ffff6617b13 in  () at /usr/lib/libgtk-3.so.0
#46 0x00007ffff661bd62 in  () at /usr/lib/libgtk-3.so.0
#47 0x00007ffff65c5144 in  () at /usr/lib/libgtk-3.so.0
#48 0x00007ffff67854b1 in  () at /usr/lib/libgtk-3.so.0
#49 0x00007ffff678574c in  () at /usr/lib/libgtk-3.so.0
#50 0x00007ffff6784ba1 in gtk_widget_get_preferred_height () at /usr/lib/libgtk-3.so.0
#51 0x00007ffff684ba83 in  () at /usr/lib/libgtk-3.so.0
---Type <return> to continue, or q <return> to quit---
#52 0x00007ffff6784ead in  () at /usr/lib/libgtk-3.so.0
#53 0x00007ffff678574c in  () at /usr/lib/libgtk-3.so.0
#54 0x00007ffff6785a55 in gtk_widget_get_preferred_height_and_baseline_for_width ()
    at /usr/lib/libgtk-3.so.0
#55 0x00007ffff6785b9c in  () at /usr/lib/libgtk-3.so.0
#56 0x00007ffff684d995 in  () at /usr/lib/libgtk-3.so.0
#57 0x00007ffff684e388 in  () at /usr/lib/libgtk-3.so.0
#58 0x00007ffff4c080e6 in  () at /usr/lib/libgobject-2.0.so.0
#59 0x00007ffff4c22f6f in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#60 0x00007ffff4c2369f in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#61 0x00007ffff6610cc9 in  () at /usr/lib/libgtk-3.so.0
#62 0x00007ffff4c07ead in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#63 0x00007ffff4c1a4ae in  () at /usr/lib/libgobject-2.0.so.0
#64 0x00007ffff4c22c85 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#65 0x00007ffff4c2369f in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#66 0x00007ffff61f2d5f in  () at /usr/lib/libgdk-3.so.0
#67 0x00007ffff61dd5e3 in  () at /usr/lib/libgdk-3.so.0
#68 0x00007ffff4930343 in  () at /usr/lib/libglib-2.0.so.0
#69 0x00007ffff492f8c5 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#70 0x00007ffff492fc88 in  () at /usr/lib/libglib-2.0.so.0
#71 0x00007ffff492fd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#72 0x00007ffff4eeb72d in g_application_run () at /usr/lib/libgio-2.0.so.0
#73 0x00007ffff6e2114f in gtkui_thread () at /usr/lib/deadbeef/ddb_gui_GTK3.so
#74 0x00007ffff6e211f2 in  () at /usr/lib/deadbeef/ddb_gui_GTK3.so
#75 0x0000555555587c9c in  ()
#76 0x00007ffff72d3f6a in __libc_start_main () at /usr/lib/libc.so.6
#77 0x0000555555587e8a in  ()
```

**Comment by Alexey-Yakovenko** [comment]
There's not much I can do with backtrace from a stripped build...
It shows that the crash happens inside of pulseaudio, but the reason could be in deadbeef code.
Hard to tell.. I'll try to reproduce.

**Comment by Alexey-Yakovenko** [comment]
I was never able to reproduce this issue.
Maybe something else fixed it.
At least the test DSF files which I have don't cause the player to crash.

**Comment by Alexey-Yakovenko** [comment]
Reopened, since I just managed to reproduce this.

**Comment by Alexey-Yakovenko** [comment]
fixed for real now.
