### ISSUE TITLE
segfault on playlist element removal (from context menu)

### ISSUE THREAD

**Issue by Bfgeshka** [DeaDBeeF-Player/deadbeef#2049]
Deadbeef version: a8292bca0f62b43c3f9dd78597ee3dd673cc9191
OS: gentoo linux

Current UI toolkit is gtk2.

```
Starting program: /usr/bin/deadbeef 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe0781700 (LWP 19740)]
[New Thread 0x7fffdff80700 (LWP 19741)]
[New Thread 0x7fffdf77f700 (LWP 19742)]
[New Thread 0x7fffdef7e700 (LWP 19743)]
[New Thread 0x7fffde77d700 (LWP 19744)]
[New Thread 0x7fffddf7c700 (LWP 19745)]
[New Thread 0x7fffdd09c700 (LWP 19746)]

Thread 1 "deadbeef-gtkui" received signal SIGSEGV, Segmentation fault.
0x00007ffff6c137f6 in on_remove2_activate (menuitem=<optimized out>, user_data=<optimized out>) at plcommon.c:799
799	    get_context_menu_listview (menuitem)->binding->delete_selected ();

Thread 8 (Thread 0x7fffdd09c700 (LWP 19746)):
#0  0x00007ffff76285ac in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555eb5de8)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555555ed8fd0, cond=0x555555eb5dc0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x555555eb5dc0, mutex=0x555555ed8fd0) at pthread_cond_wait.c:655
#3  0x00007ffff6c12abe in loading_thread (none=<optimized out>) at coverart.c:405
#4  0x00007ffff76219aa in start_thread (arg=0x7fffdd09c700) at pthread_create.c:463
#5  0x00007ffff735615f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fffddf7c700 (LWP 19745)):
#0  0x00007ffff76285ac in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555885808)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x5555558857b0, cond=0x5555558857e0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x5555558857e0, mutex=mutex@entry=0x5555558857b0) at pthread_cond_wait.c:655
#3  0x000055555559e4e1 in cond_wait (c=93824995579872, m=93824995579824) at threading_pthread.c:218
#4  0x000055555559d017 in messagepump_wait () at messagepump.c:129
#5  0x00005555555891b9 in player_mainloop () at main.c:716
#6  0x0000555555589359 in mainloop_thread (ctx=<optimized out>) at main.c:850
#7  0x00007ffff76219aa in start_thread (arg=0x7fffddf7c700) at pthread_create.c:463
#8  0x00007ffff735615f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fffde77d700 (LWP 19744)):
#0  0x00007ffff734ce7f in __GI___select (nfds=4, readfds=0x7fffde77ce50, writefds=0x0, exceptfds=0x0, timeout=0x7fffde77ce40)
    at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x0000555555588e37 in server_loop (ctx=<optimized out>) at main.c:587
#2  0x00007ffff76219aa in start_thread (arg=0x7fffde77d700) at pthread_create.c:463
#3  0x00007ffff735615f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fffdef7e700 (LWP 19743)):
#0  0x00007ffff7320628 in __GI___nanosleep (requested_time=requested_time@entry=0x7fffdef7dde0, remaining=remaining@entry=0x0)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007ffff734d894 in usleep (useconds=useconds@entry=50000) at ../sysdeps/posix/usleep.c:32
#2  0x0000555555599990 in streamer_thread (unused=<optimized out>) at streamer.c:1486
#3  0x00007ffff76219aa in start_thread (arg=0x7fffdef7e700) at pthread_create.c:463
#4  0x00007ffff735615f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fffdf77f700 (LWP 19742)):
#0  0x00007ffff7320628 in __GI___nanosleep (requested_time=requested_time@entry=0x7fffdf77edc0, remaining=remaining@entry=0x0)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007ffff734d894 in usleep (useconds=useconds@entry=200000) at ../sysdeps/posix/usleep.c:32
#2  0x00007fffe3ceb14f in hotkeys_event_loop (unused=<optimized out>) at hotkeys.c:498
#3  0x00007ffff76219aa in start_thread (arg=0x7fffdf77f700) at pthread_create.c:463
#4  0x00007ffff735615f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fffdff80700 (LWP 19741)):
#0  0x00007ffff7320628 in __GI___nanosleep (requested_time=requested_time@entry=0x7fffdff7cda0, remaining=remaining@entry=0x0)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:28
#1  0x00007ffff734d894 in usleep (useconds=useconds@entry=100000) at ../sysdeps/posix/usleep.c:32
#2  0x00007fffeba039ba in cache_cleaner_thread (none=<optimized out>) at cache.c:167
#3  0x00007ffff76219aa in start_thread (arg=0x7fffdff80700) at pthread_create.c:463
#4  0x00007ffff735615f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fffe0781700 (LWP 19740)):
#0  0x00007ffff76285ac in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5555558eda28)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x5555558ed9d0, cond=0x5555558eda00) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x5555558eda00, mutex=0x5555558ed9d0) at pthread_cond_wait.c:655
#3  0x00007fffeba03481 in fetcher_thread (none=<optimized out>) at artwork.c:1838
#4  0x00007ffff76219aa in start_thread (arg=0x7fffe0781700) at pthread_create.c:463
#5  0x00007ffff735615f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff7fccb80 (LWP 19734)):
#0  0x00007ffff6c137f6 in on_remove2_activate (menuitem=<optimized out>, user_data=<optimized out>) at plcommon.c:799
#1  0x00007ffff4d77f65 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#2  0x00007ffff4d8b0ce in ?? () from /usr/lib64/libgobject-2.0.so.0
#3  0x00007ffff4d94fce in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#4  0x00007ffff4d95a2f in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#5  0x00007ffff676cf3a in gtk_widget_activate () from /usr/lib64/libgtk-x11-2.0.so.0
#6  0x00007ffff66207f5 in gtk_menu_shell_activate_item () from /usr/lib64/libgtk-x11-2.0.so.0
#7  0x00007ffff6620b8e in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#8  0x00007ffff6612615 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#9  0x00007ffff6607ef3 in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#10 0x00007ffff4d77f65 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#11 0x00007ffff4d8ae60 in ?? () from /usr/lib64/libgobject-2.0.so.0
#12 0x00007ffff4d94d5c in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#13 0x00007ffff4d95a2f in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#14 0x00007ffff676e81c in ?? () from /usr/lib64/libgtk-x11-2.0.so.0
#15 0x00007ffff6606585 in gtk_propagate_event () from /usr/lib64/libgtk-x11-2.0.so.0
#16 0x00007ffff6606b0b in gtk_main_do_event () from /usr/lib64/libgtk-x11-2.0.so.0
#17 0x00007ffff623f7f4 in ?? () from /usr/lib64/libgdk-x11-2.0.so.0
#18 0x00007ffff434db46 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#19 0x00007ffff434dd80 in ?? () from /usr/lib64/libglib-2.0.so.0
#20 0x00007ffff434e072 in g_main_loop_run () from /usr/lib64/libglib-2.0.so.0
#21 0x00007ffff6605707 in gtk_main () from /usr/lib64/libgtk-x11-2.0.so.0
#22 0x00007ffff6be5476 in gtkui_thread (ctx=ctx@entry=0x0) at gtkui.c:1404
#23 0x00007ffff6be5512 in gtkui_start () at gtkui.c:1527
#24 0x00005555555877bc in main (argc=<optimized out>, argv=<optimized out>) at main.c:1229
```

Segfault is triggered on removing any element regardless of index or playing status (of element and playback). Deleting file itself via player context menu doesn't trigger it though, only playlist element.

**Comment by Alexey-Yakovenko** [comment]
Was expecting something like that after fixing another playlist regression. Thanks for spotting.
