### ISSUE TITLE
GME: Attempting to play game gear music causes game-music-emu-0.6pre to abort.

### ISSUE THREAD

**Issue by lighth7015** [DeaDBeeF-Player/deadbeef#2312]
### Steps to reproduce the problem
Play any Game Gear vgm.

### What's going on? Describe the problem in as much detail as possible.
```deadbeef: game-music-emu-0.6pre/gme/blargg_common.h:187: T& blargg_vector<T>::operator[](size_t) [with T = unsigned char; size_t = long unsigned int]: Assertion `n < size_' failed.
Aborted (core dumped)```

### GDB stack trace
```#0  0x00007ffff7c6ef25 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff7c58897 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff7c58767 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007ffff7c67526 in  () at /usr/lib/libc.so.6
#4  0x00007fffed4559db in  () at /usr/lib/deadbeef/gme.so
#5  0x00007fffed454e49 in Sgc_Emu::start_track_(int) () at /usr/lib/deadbeef/gme.so
#6  0x00007fffed443ca3 in gme_t::start_track(int) () at /usr/lib/deadbeef/gme.so
#7  0x00007fffed429404 in  () at /usr/lib/deadbeef/gme.so
#8  0x000055555559804d in  ()
#9  0x0000555555599b77 in  ()
#10 0x000055555559a422 in  ()
#11 0x00007ffff7e034cf in start_thread () at /usr/lib/libpthread.so.0
#12 0x00007ffff7d322d3 in clone () at /usr/lib/libc.so.6
```

### Information about the software:
Deadbeef version: 1.8.2
OS: ArchLinux (`Linux 5.4.6-arch3-1 x86_64 GNU/Linux`)

**Comment by Alexey-Yakovenko** [comment]
Can you please provide a link to an example game gear VGM that would cause the error? A random GG VGM pack that I found doesn't cause the error.

**Comment by Alexey-Yakovenko** [comment]
Stack trace with symbols

```
Thread 6 "deadbeef-stream" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffde43c700 (LWP 2092)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7261e97 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7263801 in __GI_abort () at abort.c:79
#2  0x00007ffff725339a in __assert_fail_base (fmt=0x7ffff73da7d8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7fffe965cf63 "n < size_", file=file@entry=0x7fffe965ce58 "game-music-emu-0.6pre/gme/blargg_common.h", line=line@entry=187, function=function@entry=0x7fffe9664c80 <_ZZN13blargg_vectorIhEixEmE19__PRETTY_FUNCTION__> "T& blargg_vector<T>::operator[](size_t) [with T = unsigned char; size_t = long unsigned int]") at assert.c:92
#3  0x00007ffff7253412 in __GI___assert_fail (assertion=assertion@entry=0x7fffe965cf63 "n < size_", file=file@entry=0x7fffe965ce58 "game-music-emu-0.6pre/gme/blargg_common.h", line=line@entry=187, function=function@entry=0x7fffe9664c80 <_ZZN13blargg_vectorIhEixEmE19__PRETTY_FUNCTION__> "T& blargg_vector<T>::operator[](size_t) [with T = unsigned char; size_t = long unsigned int]")
    at assert.c:101
#4  0x00007fffe95dab64 in blargg_vector<unsigned char>::operator[](unsigned long) (n=<optimized out>, this=<optimized out>)
    at game-music-emu-0.6pre/gme/blargg_common.h:187
#5  0x00007fffe95dab64 in Sgc_Impl::start_track(int) (this=0x7fffc400f570, track=0) at game-music-emu-0.6pre/gme/Sgc_Impl.cpp:95
#6  0x00007fffe95da027 in Sgc_Emu::start_track_(int) (this=0x7fffc400f350, track=0) at game-music-emu-0.6pre/gme/Sgc_Emu.cpp:152
#7  0x00007fffe95c9383 in gme_t::start_track(int) (this=0x7fffc400f350, track=0) at game-music-emu-0.6pre/gme/Music_Emu.cpp:200
#8  0x00007fffe95e47a5 in gme_start_track(Music_Emu*, int) (gme=<optimized out>, index=<optimized out>) at game-music-emu-0.6pre/gme/gme.cpp:347
#9  0x00007fffe95aea87 in cgme_init (_info=0x7fffc4003000, it=0x5555558a9260)
---Type <return> to continue, or q <return> to quit---
    at cgme.c:227
#10 0x00005555555979b6 in stream_track (it=it@entry=0x5555558a9260, startpaused=startpaused@entry=0) at streamer.c:1259
#11 0x0000555555599b04 in _play_track (it=0x5555558a9260, startpaused=0)
    at streamer.c:2366
#12 0x000055555559a2cc in play_index (startpaused=<optimized out>, idx=<optimized out>) at streamer.c:2420
#13 0x000055555559a2cc in streamer_thread (unused=<optimized out>)
    at streamer.c:1588
#14 0x00007ffff761b6db in start_thread (arg=0x7fffde43c700)
    at pthread_create.c:463
#15 0x00007ffff734488f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
