### ISSUE TITLE
Adding and removing Album Art column crashes DB

### ISSUE THREAD

**Issue by JakeSFR** [DeaDBeeF-Player/deadbeef#2326]
Linux, latest static build.
Happens with both GTK2 and 3.
Tried also with some of the other columns, but apparently it only concerns Album Art.

0. Fresh start with a new profile (deleted ~/.config/deadbeef).
1. Add 'Album Art' column.
2. Remove it.
3. Repeat 1 and 2 until DB crashes.

It crashes with either:

```
Segmentation Fault
backtrace() returned 24 addresses
./deadbeef() [0x403d53]
/lib64/libc.so.6(+0x34f20) [0x7efc99532f20]
/usr/lib64/libgtk-x11-2.0.so.0(gtk_window_list_toplevels+0xf) [0x7efc98e2e945]
/usr/lib64/libgtk-x11-2.0.so.0(+0x1122a9) [0x7efc98d462a9]
/usr/lib64/libgtk-x11-2.0.so.0(gtk_menu_popup+0x468) [0x7efc98d509e0]
/home/testuser/deadbeef-devel/plugins/ddb_gui_GTK2.so(pl_common_header_context_menu+0x48b) [0x7efc992883ab]
/home/testuser/deadbeef-devel/plugins/ddb_gui_GTK2.so(+0x83e50) [0x7efc99271e50]
/usr/lib64/libgtk-x11-2.0.so.0(+0x114b30) [0x7efc98d48b30]
/usr/lib64/libgobject-2.0.so.0(g_closure_invoke+0x102) [0x7efc98031066]
/usr/lib64/libgobject-2.0.so.0(+0x1c1b3) [0x7efc9803d1b3]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit_valist+0x8d4) [0x7efc98040b59]
/usr/lib64/libgobject-2.0.so.0(g_signal_emit+0x82) [0x7efc98040d6a]
/usr/lib64/libgtk-x11-2.0.so.0(+0x1ec7ed) [0x7efc98e207ed]
/usr/lib64/libgtk-x11-2.0.so.0(gtk_propagate_event+0x13a) [0x7efc98d473f2]
/usr/lib64/libgtk-x11-2.0.so.0(gtk_main_do_event+0x385) [0x7efc98d477bc]
/usr/lib64/libgdk-x11-2.0.so.0(+0x4f50d) [0x7efc984cc50d]
/usr/lib64/libglib-2.0.so.0(g_main_context_dispatch+0x107) [0x7efc97d71c75]
/usr/lib64/libglib-2.0.so.0(+0x41e9d) [0x7efc97d71e9d]
/usr/lib64/libglib-2.0.so.0(g_main_loop_run+0xdd) [0x7efc97d7214a]
/usr/lib64/libgtk-x11-2.0.so.0(gtk_main+0x9d) [0x7efc98d46a17]
/home/testuser/deadbeef-devel/plugins/ddb_gui_GTK2.so(+0x62ba1) [0x7efc99250ba1]
./deadbeef() [0x403a63]
/lib64/libc.so.6(__libc_start_main+0xe7) [0x7efc9951fab7]
./deadbeef() [0x403c5b]

```
or:

```
malloc(): smallbin double linked list corrupted
Aborted
```

GDB backtrace:

```
Starting program: /home/testuser/deadbeef-devel/deadbeef 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe8436700 (LWP 24359)]
[New Thread 0x7fffe7c35700 (LWP 24360)]
[New Thread 0x7fffe7434700 (LWP 24361)]
[New Thread 0x7fffe6c33700 (LWP 24362)]
[New Thread 0x7fffe63b4700 (LWP 24366)]
[New Thread 0x7fffef737700 (LWP 24376)]
[New Thread 0x7fffeef36700 (LWP 24377)]
[New Thread 0x7fffe5bb3700 (LWP 24393)]

Thread 1 "deadbeef-main" received signal SIGABRT, Aborted.
0x00007ffff729ae9b in raise () from /lib64/libc.so.6

Thread 9 (Thread 0x7fffe5bb3700 (LWP 24393)):
#0  0x00007ffff762d5ac in pthread_cond_wait () at /lib64/libpthread.so.0
#1  0x00007ffff6fea5ab in  ()
    at /home/testuser/deadbeef-devel/plugins/ddb_gui_GTK2.so
#2  0x00007ffff76275aa in start_thread () at /lib64/libpthread.so.0
#3  0x00007ffff735cc5f in clone () at /lib64/libc.so.6

Thread 8 (Thread 0x7fffeef36700 (LWP 24377)):
#0  0x00007ffff762d5ac in pthread_cond_wait () at /lib64/libpthread.so.0
#1  0x0000000000421083 in  ()
#2  0x000000000041fdb7 in  ()
#3  0x0000000000405169 in  ()
#4  0x0000000000405189 in  ()
#5  0x00007ffff76275aa in start_thread () at /lib64/libpthread.so.0
#6  0x00007ffff735cc5f in clone () at /lib64/libc.so.6

Thread 7 (Thread 0x7fffef737700 (LWP 24376)):
#0  0x00007ffff735490f in select () at /lib64/libc.so.6
#1  0x0000000000404e31 in  ()
#2  0x00007ffff76275aa in start_thread () at /lib64/libpthread.so.0
#3  0x00007ffff735cc5f in clone () at /lib64/libc.so.6

Thread 6 (Thread 0x7fffe63b4700 (LWP 24366)):
#0  0x00007ffff732a460 in nanosleep () at /lib64/libc.so.6
#1  0x00007ffff7355134 in usleep () at /lib64/libc.so.6
#2  0x000000000041c816 in  ()
#3  0x00007ffff76275aa in start_thread () at /lib64/libpthread.so.0
#4  0x00007ffff735cc5f in clone () at /lib64/libc.so.6

Thread 5 (Thread 0x7fffe6c33700 (LWP 24362)):
#0  0x00007ffff762d5ac in pthread_cond_wait () at /lib64/libpthread.so.0
#1  0x0000000000421083 in  ()
#2  0x00007fffebdcedb8 in  ()
    at /home/testuser/deadbeef-devel/plugins/lastfm.so
#3  0x00007ffff76275aa in start_thread () at /lib64/libpthread.so.0
#4  0x00007ffff735cc5f in clone () at /lib64/libc.so.6

Thread 4 (Thread 0x7fffe7434700 (LWP 24361)):
#0  0x00007ffff732a460 in nanosleep () at /lib64/libc.so.6
#1  0x00007ffff7355134 in usleep () at /lib64/libc.so.6
#2  0x00007fffec311252 in  ()
    at /home/testuser/deadbeef-devel/plugins/hotkeys.so
#3  0x00007ffff76275aa in start_thread () at /lib64/libpthread.so.0
#4  0x00007ffff735cc5f in clone () at /lib64/libc.so.6

Thread 3 (Thread 0x7fffe7c35700 (LWP 24360)):
#0  0x00007ffff762d96a in pthread_cond_timedwait () at /lib64/libpthread.so.0
#1  0x00007fffefdc89e7 in  ()
    at /home/testuser/deadbeef-devel/plugins/artwork.so
#2  0x00007ffff76275aa in start_thread () at /lib64/libpthread.so.0
#3  0x00007ffff735cc5f in clone () at /lib64/libc.so.6

Thread 2 (Thread 0x7fffe8436700 (LWP 24359)):
#0  0x00007ffff762d5ac in pthread_cond_wait () at /lib64/libpthread.so.0
#1  0x00007fffefdc79c1 in  ()
    at /home/testuser/deadbeef-devel/plugins/artwork.so
#2  0x00007ffff76275aa in start_thread () at /lib64/libpthread.so.0
#3  0x00007ffff735cc5f in clone () at /lib64/libc.so.6

Thread 1 (Thread 0x7ffff7ff3f00 (LWP 24080)):
#0  0x00007ffff729ae9b in raise () at /lib64/libc.so.6
#1  0x00007ffff729c251 in abort () at /lib64/libc.so.6
#2  0x00007ffff72dd7c7 in __libc_message () at /lib64/libc.so.6
#3  0x00007ffff72e3d6a in  () at /lib64/libc.so.6
#4  0x00007ffff72e715c in _int_malloc () at /lib64/libc.so.6
#5  0x00007ffff72e7d85 in _int_realloc () at /lib64/libc.so.6
#6  0x00007ffff72e8feb in realloc () at /lib64/libc.so.6
#7  0x00007ffff5addb58 in g_realloc (mem=<optimized out>, n_bytes=64)
    at gmem.c:164
#8  0x00007ffff6214121 in miUnionNonO (pReg=0x82eed0, r=0x82eee8, rEnd=0x82eef8, y1=114, y2=263) at gdkregion-generic.c:1115
#9  0x00007ffff6213fbf in miRegionOp (newReg=0x82eed0, reg1=<optimized out>, reg2=<optimized out>, overlapFn=0x7ffff621416b <miUnionO>, nonOverlap1Fn=0x7ffff6214095 <miUnionNonO>, nonOverlap2Fn=0x7ffff6214095 <miUnionNonO>)
    at gdkregion-generic.c:1021
#10 0x00007ffff6214c2f in IA__gdk_region_union (source1=0x82eed0, source2=0xa10d90) at gdkregion-generic.c:1266
#11 0x00007ffff621c3a8 in gdk_window_invalidate_maybe_recurse_full (window=0x9665a0 [GdkWindow], region=0x9fb630, clear_bg=CLEAR_BG_NONE, child_func=
    0x7ffff621a388 <true_predicate>, user_data=0x0) at gdkwindow.c:6036
#12 0x00007ffff621c4b5 in gdk_window_invalidate_rect_full (window=0x9665a0 [GdkWindow], rect=<optimized out>, invalidate_children=1, clear_bg=CLEAR_BG_NONE)
    at gdkwindow.c:5873
#13 0x00007ffff6b88cff in IA__gtk_widget_queue_draw_area (widget=widget@entry=0x8954e0 [GtkDrawingArea], x=0, y=0, width=500, height=23) at gtkwidget.c:3706
#14 0x00007ffff6b8e345 in IA__gtk_widget_queue_draw (widget=0x8954e0 [GtkDrawingArea]) at gtkwidget.c:3776
#15 0x00007ffff6fd9063 in ddb_listview_refresh ()
    at /home/testuser/deadbeef-devel/plugins/ddb_gui_GTK2.so
#19 0x00007ffff5da8d6a in <emit signal ??? on instance 0x9fc820 [GtkMenuItem]> (instance=instance@entry=0x9fc820, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3447
    #16 0x00007ffff5d99066 in g_closure_invoke (closure=0xa39fa0, return_value=0x0, n_param_values=1, param_values=0x7fffffffc8f0, invocation_hint=0x7fffffffc898) at gclosure.c:810
    #17 0x00007ffff5da4f89 in signal_emit_unlocked_R (node=node@entry=0x82dbb0, detail=detail@entry=0, instance=instance@entry=0x9fc820, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffc8f0) at gsignal.c:3635
    #18 0x00007ffff5da8af5 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffca48) at gsignal.c:3391
#20 0x00007ffff6b878f6 in IA__gtk_widget_activate (widget=widget@entry=0x9fc820 [GtkMenuItem]) at gtkwidget.c:5041
#21 0x00007ffff6abf8cb in IA__gtk_menu_shell_activate_item (menu_shell=0xa04e10 [GtkMenu], menu_item=0x9fc820 [GtkMenuItem], force_deactivate=<optimized out>)
    at gtkmenushell.c:1278
#22 0x00007ffff6abf9fa in gtk_menu_shell_button_release (widget=0xa04e10 [GtkMenu], event=0xa40f50) at gtkmenushell.c:703
#27 0x00007ffff5da8d6a in <emit signal ??? on instance 0xa04e10 [GtkMenu]> (instance=instance@entry=0xa04e10, signal_id=<optimized out>, detail=detail@entry=0)
    at gsignal.c:3447
    #23 0x00007ffff6ab0b30 in _gtk_marshal_BOOLEAN__BOXED (closure=0x829550, return_value=0x7fffffffccc0, n_param_values=<optimized out>, param_values=0x7fffffffcd40, invocation_hint=<optimized out>, marshal_data=<optimized out>)
    at gtkmarshalers.c:84
    #24 0x00007ffff5d99066 in g_closure_invoke (closure=0x829550, return_value=0x7fffffffccc0, n_param_values=2, param_values=0x7fffffffcd40, invocation_hint=0x7fffffffcce8) at gclosure.c:810
    #25 0x00007ffff5da50c8 in signal_emit_unlocked_R (node=node@entry=0x8298d0, detail=detail@entry=0, instance=instance@entry=0xa04e10, emission_return=emission_return@entry=0x7fffffffcdf8, instance_and_params=instance_and_params@entry=0x7fffffffcd40) at gsignal.c:3673
    #26 0x00007ffff5da8b59 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffcea8) at gsignal.c:3401
#28 0x00007ffff6b887ed in gtk_widget_event_internal (widget=widget@entry=0xa04e10 [GtkMenu], event=event@entry=0xa40f50) at gtkwidget.c:5010
#29 0x00007ffff6b88989 in IA__gtk_widget_event (widget=widget@entry=0xa04e10 [GtkMenu], event=event@entry=0xa40f50) at gtkwidget.c:4807
#30 0x00007ffff6aaf3f2 in IA__gtk_propagate_event (widget=0xa04e10 [GtkMenu], event=0xa40f50) at gtkmain.c:2503
#31 0x00007ffff6aaf7bc in IA__gtk_main_do_event (event=<optimized out>)
    at gtkmain.c:1698
#32 0x00007ffff623450d in gdk_event_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at gdkevents-x11.c:2425
#33 0x00007ffff5ad9c75 in g_main_dispatch (context=0x8217c0) at gmain.c:3182
#34 0x00007ffff5ad9c75 in g_main_context_dispatch (context=context@entry=0x8217c0) at gmain.c:3847
#35 0x00007ffff5ad9e9d in g_main_context_iterate (context=0x8217c0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3920
#36 0x00007ffff5ada14a in g_main_loop_run (loop=0x9580e0) at gmain.c:4116
#37 0x00007ffff6aaea17 in IA__gtk_main () at gtkmain.c:1270
#38 0x00007ffff6fb8ba1 in  ()
    at /home/testuser/deadbeef-devel/plugins/ddb_gui_GTK2.so
#39 0x0000000000403a63 in  ()
#40 0x00007ffff7287ab7 in __libc_start_main () at /lib64/libc.so.6
#41 0x0000000000403c5b in  ()
```

**Comment by Alexey-Yakovenko** [comment]
Indeed.. It also crashes on quit.

**Comment by Alexey-Yakovenko** [comment]
I reverted the change which causes this. It may still crash on quit though. Needs a closer look.

**Comment by JakeSFR** [comment]
Ok, thanks!
