### ISSUE TITLE
Cue: infinite recursion with self-referring cue file

### ISSUE THREAD

**Issue by kuba160** [DeaDBeeF-Player/deadbeef#2375]
### Steps to reproduce the problem
Have a cue file that references itself. Example entry of file `testfile.cue`:

```FILE "testfile.cue" WAVE```

### What's going on? Describe the problem in as much detail as possible.

```
^^^
#2213 0x000055555558eb04 in plt_load_cuesheet_from_buffer (plt=plt@entry=0x7fffb4015cf0, after=after@entry=0x0, fname=fname@entry=0x7fffaf7f1510 "/home/kuba/cue/cuefile.cue", embedded_origin=embedded_origin@entry=0x0, embedded_numsamples=embedded_numsamples@entry=0, embedded_samplerate=embedded_samplerate@entry=0, buffer=<optimized out>, sz=1829, dirname=<optimized out>, namelist=<optimized out>, n=<optimized out>) at cueutil.c:806
#2214 0x000055555558f56a in plt_load_cue_file (plt=plt@entry=0x7fffb4015cf0, after=after@entry=0x0, fname=0x7fffaf7f1510 "/home/kuba/cue/cuefile.cue", fname@entry=0x7fffaf7f2798 "/home/kuba/cue/cuefile.cue", dirname=dirname@entry=0x0, namelist=namelist@entry=0x0, n=n@entry=0) at cueutil.c:470
#2215 0x0000555555591807 in plt_insert_file_int (visibility=visibility@entry=-1, playlist=0x7fffb4015cf0, after=after@entry=0x0, fname=fname@entry=0x7fffaf7f2798 "/home/kuba/cue/cuefile.cue", pabort=pabort@entry=0x0, cb=cb@entry=0x0, user_data=<optimized out>) at playlist.c:989
#2216 0x0000555555597239 in plt_insert_file2 (visibility=visibility@entry=-1, playlist=<optimized out>, after=after@entry=0x0, fname=fname@entry=0x7fffaf7f2798 "/home/kuba/cue/cuefile.cue", pabort=pabort@entry=0x0, callback=callback@entry=0x0, user_data=0x0) at playlist.c:3745
#2217 0x000055555558e10f in _load_nextfile (cue=cue@entry=0x7fffaf7f2740) at cueutil.c:589
#2218 0x000055555558eb04 in plt_load_cuesheet_from_buffer (plt=plt@entry=0x7fffb40124f0, after=after@entry=0x0, fname=fname@entry=0x7fffaf7f5eb0 "/home/kuba/cue/cuefile.cue", embedded_origin=embedded_origin@entry=0x0, embedded_numsamples=embedded_numsamples@entry=0, embedded_samplerate=embedded_samplerate@entry=0, buffer=<optimized out>, sz=1829, dirname=<optimized out>, namelist=<optimized out>, n=<optimized out>) at cueutil.c:806
#2219 0x000055555558f56a in plt_load_cue_file (plt=plt@entry=0x7fffb40124f0, after=after@entry=0x0, fname=0x7fffaf7f5eb0 "/home/kuba/cue/cuefile.cue", fname@entry=0x7fffaf7f7138 "/home/kuba/cue/cuefile.cue", dirname=dirname@entry=0x0, namelist=namelist@entry=0x0, n=n@entry=0) at cueutil.c:470
#2220 0x0000555555591807 in plt_insert_file_int (visibility=visibility@entry=-1, playlist=0x7fffb40124f0, after=after@entry=0x0, fname=fname@entry=0x7fffaf7f7138 "/home/kuba/cue/cuefile.cue", pabort=pabort@entry=0x0, cb=cb@entry=0x0, user_data=<optimized out>) at playlist.c:989
#2221 0x0000555555597239 in plt_insert_file2 (visibility=visibility@entry=-1, playlist=<optimized out>, after=after@entry=0x0, fname=fname@entry=0x7fffaf7f7138 "/home/kuba/cue/cuefile.cue", pabort=pabort@entry=0x0, callback=callback@entry=0x0, user_data=0x0) at playlist.c:3745
#2222 0x000055555558e10f in _load_nextfile (cue=cue@entry=0x7fffaf7f70e0) at cueutil.c:589
#2223 0x000055555558eb04 in plt_load_cuesheet_from_buffer (plt=plt@entry=0x555555eac080, after=after@entry=0x0, fname=fname@entry=0x7fffaf7fa850 "/home/kuba/cue/cuefile.cue", embedded_origin=embedded_origin@entry=0x0, embedded_numsamples=embedded_numsamples@entry=0, embedded_samplerate=embedded_samplerate@entry=0, buffer=<optimized out>, sz=1829, dirname=<optimized out>, namelist=<optimized out>, n=<optimized out>) at cueutil.c:806
#2224 0x000055555558f56a in plt_load_cue_file (plt=plt@entry=0x555555eac080, after=after@entry=0x0, fname=0x7fffaf7fa850 "/home/kuba/cue/cuefile.cue", fname@entry=0x7fffaf7fb9c0 "/home/kuba/cue/cuefile.cue", dirname=dirname@entry=0x7fffaf7fc9c0 "/home/kuba/cue", namelist=0x7fffb4012400, n=n@entry=4) at cueutil.c:470
#2225 0x0000555555591c45 in plt_insert_dir_int (visibility=visibility@entry=0, playlist=playlist@entry=0x555555eac080, vfs=vfs@entry=0x0, after=0x0, dirname=dirname@entry=0x555555c57630 "/home/kuba/cue", pabort=pabort@entry=0x7fffaf7fda34, cb=<optimized out>, user_data=<optimized out>) at playlist.c:1250
#2226 0x00005555555971d9 in plt_add_dir2 (visibility=0, plt=0x555555eac080, dirname=0x555555c57630 "/home/kuba/cue", callback=0x0, user_data=0x0) at playlist.c:3732
```

### Information about the software:

Deadbeef version: 40dfac893746f13d1417076e4af1c6615ba5b8f6
OS: Ubuntu 19.10

**Comment by Alexey-Yakovenko** [comment]
That's nasty.. Is it a valid cue file, or just a specially formed one to make it crash?

**Comment by kuba160** [comment]
According to @Keith-Cancel, he had some cue files that referred to itself. You can look at issue here: https://github.com/DeaDBeeF-for-Windows/deadbeef/issues/16
