### ISSUE TITLE
Some m4a audio files crash the application

### ISSUE THREAD

**Issue by fulalas** [DeaDBeeF-Player/deadbeef#2509]
Here's an example that crashes current 1.8.6 (including the static build):

https://www.mediafire.com/file/m1j4x656fgtwfbs/test1.m4a

The same file opens OK on mpv and audacious.

**Comment by spvkgn** [comment]
gdb backtrace
```

Thread 20 "deadbeef-main" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc9f22700 (LWP 1014618)]
__strcasecmp_l_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:252
252	../sysdeps/x86_64/multiarch/../strcmp.S: Нет такого файла или каталога.
(gdb) thread apply all backtrace

Thread 20 (Thread 0x7fffc9f22700 (LWP 1014618)):
#0  __strcasecmp_l_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:252
#1  0x00007ffff7fbea8c in mp4_load_tags (mp4file=<optimized out>, it=0x7fffc0002a50) at mp4tagutil.c:533
#2  0x00007ffff7fbd676 in _mp4_insert (fname=<optimized out>, fp=<optimized out>, plt=<optimized out>, after=<optimized out>) at aac.c:1024
#3  aac_insert (plt=<optimized out>, after=<optimized out>, fname=<optimized out>) at aac.c:1040
#4  0x000000000040c3de in plt_insert_file_int (visibility=0, playlist=<optimized out>, after=0x7ffff7fc5b30, fname=<optimized out>, pabort=0x7fffc9f21e8c, cb=0x0, user_data=0x0) at playlist.c:1052
#5  0x0000000000411e62 in plt_add_file_int (visibility=1819047264, plt=0x7ffff7fc5b30, fname=0xe <error: Cannot access memory at address 0xe>, cb=0x7ffff7da3090 <__memcpy_ssse3+9216>, user_data=<optimized out>) at playlist.c:1352
#6  plt_add_file2 (visibility=1819047264, plt=0x7ffff7fc5b30, fname=0xe <error: Cannot access memory at address 0xe>, callback=0x7ffff7da3090 <__memcpy_ssse3+9216>, user_data=<optimized out>) at playlist.c:3795
#7  0x00007ffff787f111 in gtkpl_addfile_cb (data=0xff69d0, userdata=<optimized out>) at fileman.c:84
#8  0x00007ffff6962ab0 in g_slist_foreach () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff787f07e in gtkpl_add_files (lst=0xe0c800) at fileman.c:97
#10 0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 18 (Thread 0x7fffe2ffd700 (LWP 1014573)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff69905a6 in g_cond_wait_until () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6913561 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff696d32a in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff696c931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 17 (Thread 0x7fffc8e98700 (LWP 1014518)):
#0  0x00007ffff7d4d96f in __GI___poll (fds=0xdb2db0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff69431ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff69432e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fffca7c899d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007ffff696c931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 13 (Thread 0x7fffcb4ae700 (LWP 1014186)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x485e98) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0xa41d40, cond=0x485e70) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x485e70, mutex=0xa41d40) at pthread_cond_wait.c:638
#3  0x00007ffff788880b in loading_thread (none=<optimized out>) at coverart.c:405
#4  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 12 (Thread 0x7fffcbfff700 (LWP 1014185)):
#0  0x00007ffff7d18361 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7fffcbffedd0, rem=rem@entry=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
#1  0x00007ffff7d1deb7 in __GI___nanosleep (requested_time=requested_time@entry=0x7fffcbffedd0, remaining=remaining@entry=0x0) at nanosleep.c:27
#2  0x00007ffff7d5082f in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#3  0x00007fffebb5446a in hotkeys_event_loop (unused=<optimized out>) at hotkeys.c:501
#4  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

--Type <RET> for more, q to quit, c to continue without paging--
Thread 11 (Thread 0x7fffe0ff9700 (LWP 1014184)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x49284c) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x4927f0, cond=0x492820) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x492820, mutex=0x4927f0) at pthread_cond_wait.c:638
#3  0x000000000041cd90 in cond_wait (c=4794400, m=4794352) at threading_pthread.c:221
#4  0x000000000041ba44 in messagepump_wait () at messagepump.c:130
#5  0x000000000040499d in player_mainloop () at main.c:831
#6  0x0000000000405f96 in mainloop_thread (ctx=0x49284c) at main.c:965
#7  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7fffe17fa700 (LWP 1014183)):
#0  0x00007ffff7d4ff9b in __GI___select (nfds=4, readfds=0x7fffe17f9e58, writefds=0x0, exceptfds=0x0, timeout=0x7fffe17f9e40) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x000000000040482f in server_loop (ctx=<optimized out>) at main.c:694
#2  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#3  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7fffe1ffb700 (LWP 1014182)):
#0  0x00007ffff7d18361 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7fffe1ffae00, rem=rem@entry=0x0) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
#1  0x00007ffff7d1deb7 in __GI___nanosleep (requested_time=requested_time@entry=0x7fffe1ffae00, remaining=remaining@entry=0x0) at nanosleep.c:27
#2  0x00007ffff7d5082f in usleep (useconds=<optimized out>) at ../sysdeps/posix/usleep.c:32
#3  0x00000000004143ca in streamer_thread (unused=<optimized out>) at streamer.c:835
#4  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7fffe27fc700 (LWP 1014181)):
#0  0x00007ffff7d4d96f in __GI___poll (fds=0x12cd610, nfds=7, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff69431ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6943533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6b98eda in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff696c931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fffe37fe700 (LWP 1014179)):
#0  0x00007ffff7d4d96f in __GI___poll (fds=0x7fffdc008440, nfds=2, timeout=477) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff69431ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff69432e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff6943331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff696c931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fffe3fff700 (LWP 1014178)):
#0  0x00007ffff7d4d96f in __GI___poll (fds=0x7fffdc0164d0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff69431ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff6943533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fffea861e33 in startServer () from /usr/lib/x86_64-linux-gnu/deadbeef/mpris.so
#4  0x00007ffff696c931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
--Type <RET> for more, q to quit, c to continue without paging--

Thread 4 (Thread 0x7fffe8b7e700 (LWP 1014177)):
#0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7fffe8b7bec0, clockid=<optimized out>, expected=0, futex_word=0x547308) at ../sysdeps/nptl/futex-internal.h:320
#1  __pthread_cond_wait_common (abstime=0x7fffe8b7bec0, clockid=<optimized out>, mutex=0x4cc8e0, cond=0x5472e0) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=0x5472e0, mutex=0x4cc8e0, abstime=0x7fffe8b7bec0) at pthread_cond_wait.c:656
#3  0x00007ffff484272d in cache_cleaner_thread (none=<optimized out>) at cache.c:185
#4  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fffe937f700 (LWP 1014176)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x547088) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x4cd650, cond=0x547060) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x547060, mutex=0x4cd650) at pthread_cond_wait.c:638
#3  0x00007ffff484025c in fetcher_thread (none=<optimized out>) at artwork.c:1899
#4  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#5  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fffe9b80700 (LWP 1014175)):
#0  0x00007ffff7d4ff9b in __GI___select (nfds=5, readfds=0x7fffe9b7fe60, writefds=0x0, exceptfds=0x0, timeout=0x0) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x00007ffff4b76f0d in helper_thread () from /home/pavel/.local/lib/deadbeef/signals.so
#2  0x00007ffff7e33609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#3  0x00007ffff7d5a103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff7c36b80 (LWP 1014128)):
#0  0x00007ffff7d4d96f in __GI___poll (fds=0x7fffffffb318, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff62f8c1a in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007ffff62fa61f in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007ffff62fa796 in xcb_wait_for_reply64 () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#4  0x00007ffff67ddd38 in _XReply () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007ffff67c3788 in XGetWindowProperty () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007ffff6fc09f5 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#7  0x00007ffff6fc0db8 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#8  0x00007ffff6fbd4d0 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#9  0x00007ffff73f69d0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff73f950a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff73ff8ff in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff6a2ea56 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff6a4db28 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff6a4e0d3 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff73fb24e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff6a2e802 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff6a42962 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff6a4db9e in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff6a4e0d3 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff73e743e in gtk_widget_show () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff787da1e in gtkui_progress_show_idle (data=<optimized out>) at progress.c:96
#22 0x00007ffff6942e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff6943240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff69432e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff6b5cfd5 in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#26 0x00007ffff7856c0b in gtkui_start () at gtkui.c:1540
#27 0x0000000000405e32 in main (argc=1, argv=<optimized out>) at main.c:1384
```

**Comment by Alexey-Yakovenko** [comment]
Thanks for spotting and reporting this. I didn't have such sample files before, and didn't know about the issue.
It helped to fix 2 issues -- the crash that you reported, and writing tags into that file.

**Comment by fulalas** [comment]
Cool! Thanks :)
